import { z } from 'zod';

/** Every entity is keyed by a UUID v4 generated by Postgres. */
export const idSchema = z.uuid();
export type Id = z.infer<typeof idSchema>;

/** Timestamps cross the wire as UTC ISO-8601 strings, never as local time. */
export const timestampSchema = z.iso.datetime();
export type Timestamp = z.infer<typeof timestampSchema>;

/** Monetary amounts cross the wire as integer tiyin. */
export const tiyinSchema = z.int();

export const paginationQuerySchema = z.object({
  limit: z.coerce.number().int().min(1).max(200).default(50),
  offset: z.coerce.number().int().min(0).default(0),
});
export type PaginationQuery = z.infer<typeof paginationQuerySchema>;

/** Envelope for every list endpoint, so clients page uniformly. */
export function paginatedSchema<T extends z.ZodTypeAny>(item: T) {
  return z.object({
    items: z.array(item),
    total: z.int().nonnegative(),
    limit: z.int().positive(),
    offset: z.int().nonnegative(),
  });
}

/** Shape of every non-2xx response body. */
export const apiErrorSchema = z.object({
  error: z.object({
    code: z.string(),
    message: z.string(),
    /** Field-level detail, present on validation failures. */
    details: z.unknown().optional(),
  }),
});
export type ApiError = z.infer<typeof apiErrorSchema>;

/** Stable error codes the clients branch on. */
export const API_ERROR_CODES = {
  VALIDATION_FAILED: 'validation_failed',
  UNAUTHORIZED: 'unauthorized',
  FORBIDDEN: 'forbidden',
  NOT_FOUND: 'not_found',
  CONFLICT: 'conflict',
  VEHICLE_UNAVAILABLE: 'vehicle_unavailable',
  /** Held by another rider — distinct from `vehicle_unavailable` because it
   *  clears by itself, and the app says "try again shortly" rather than
   *  "pick another scooter". */
  VEHICLE_RESERVED: 'vehicle_reserved',
  UNLOCK_FAILED: 'unlock_failed',
  OUTSIDE_PARKING_ZONE: 'outside_parking_zone',
  INSIDE_FORBIDDEN_ZONE: 'inside_forbidden_zone',
  OUTSIDE_SERVICE_AREA: 'outside_service_area',
  RIDE_ALREADY_ACTIVE: 'ride_already_active',
  /** Signed in, but no verified phone yet — Google and Telegram accounts
   *  start without one. The app routes to the link-phone flow rather than
   *  showing a generic failure. */
  PHONE_REQUIRED: 'phone_required',
  INSUFFICIENT_BALANCE: 'insufficient_balance',
  PAYMENT_FAILED: 'payment_failed',
  NOT_IMPLEMENTED: 'not_implemented',
  INTERNAL: 'internal',
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
